### ISSUE TITLE
lua脚本是如何运行的

### ISSUE THREAD

**Issue by gyhkevin** [gotomicro/redis-lock#3]
能够理解将go编译后的二进制文件打包进了docker里面，直接运行就好了，但是了解到lua是解释型语言，不需要打包lua的解释器吗

**Comment by flycash** [comment]
不需要，这个 lua 脚本是发送过去 Redis 服务端，Redis 去解释，我们自己是不需要的

**Comment by gyhkevin** [comment]
了解，谢谢~
